server:
  port: 9195

spring:
  application:
    name: OAUTH2-SERVICE
    servlet:
      context-path: /oauth2
    use-forward-headers: false

  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:userInfodb
    username: sa
    password: password
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    # DDL
    generate-dll: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: true

  security:
    enabled: true
#    user:
#      name: User
#      password: $2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
#      roles: USER, ADMIN

    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

# logging
#logging:
#  file:
#    path: ${HOME}/Documents/ms_logs/${spring.application.name}-logs
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
#    org.springframework.security: DEBUG

#    oauth2:
#      client:
#        registration:
#          github.client-id:
#          github.client-secret:
