server:
  port: 8181

  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

  security:
    enabled: true
    user:
      name: Edureka
      password: password  #$2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
      roles: USER, ADMIN

  ##  API GATEWAY CONFIGURATION
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      routes:
        - id: BOOK-MICROSERVICE
          uri: lb://BOOK-MICROSERVICE       #uri: http://localhost:8097/       #
          predicates:
            - Path=/book/**
            - Method=GET,POST,DELETE
          filters:
            - RewritePath=/book/(?<path>.*), /$\{path}
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                value: BOOK-MICROSERVICE
                fallbackuri: forward:/bookFallBack
            # - RewritePath=/book/(?<path>.*), /$\{path}  # /dummy-bookms/(?<path>.*), /$\{path}


        - id: ISSUER-MICROSERVICE
          uri: lb://ISSUER-MICROSERVICE     #uri: http://localhost:8099/      #
          predicates:
            - Path=/issuer/**
            - Method=GET,POST,DELETE
          filters:
            - RewritePath=/issuer/(?<path>.*), /$\{path}
            # - RewritePath=/issuer/(?<path>.*), /$\{path}  # /dummy-issuerms/(?<path>.*), /$\{path}
            #            - StripPrefix=1
            #            - name: CircuitBreaker
            #              args:
            #                name: ISSUER-MICROSERVICE
            #                fallbackuri: forward:/issuerFallBack

        - id: OAUTH2-SERVICE
          uri: lb://OAUTH2-SERVICE     #uri: http://localhost:9195/      #
          predicates:
            - Path=/oauth2-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/oauth2-service/(?<path>.*), /$\{path}
            #- RewritePath=/oauth2-service/(?<path>.*), /$\{path}  # /dummy-oauth2-service/(?<path>.*), /$\{path}
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#              name: OAUTH2-SERVICE
#              fallbackuri: forward:/oauthFallBack

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    #${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    hostname: localhost

# info endpoints configuration
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    java:
      version: ${java.version}

# logging
logging:
  file:
    path:  logs/log-${spring.application.name}
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:  [ "health","prometheus","metrics","gateway","hystrix.stream","mappings","traces"] #'*'
      base-path: /actuator
  endpoint:
    #   shutdown:
    #     enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always





