server:
  port: 8989
  error:
    path: /error
#    whitelabel:
#      enabled: false

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
    allow-bean-definition-overriding:  true
  security:
    enabled: true
    user:
      name: User
      password: password  #$2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
      roles: USER, ADMIN
  ##  API GATEWAY CONFIGURATION
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: book-ms
        uri: lb://BOOK-MICROSERVICE
        predicates:
          - Path=/books/**
        #  - Method=GET,POST,DELETE
        filters:
          - name: CircuitBreaker
            args:
              name: book-ms
              fallbackuri: forward:/bookFallBack
          - RewritePath=/books/(?<segment>.*), /$\{segment}
          #- RedirectTo=302, /error
          #- SetPath=/book
      - id: issuer-ms
        uri: lb://ISSUER-MICROSERVICE
        predicates:
          - Path=/issuances/**
        #  - Method=GET,POST,DELETE
        filters:
          - name: CircuitBreaker
            args:
              name: issuer-ms
              fallbackuri: forward:/issuerFallBack
          - RewritePath=/issuances/(?<segment>.*), /$\{segment}
          #- RedirectTo=302, /error
          #- SetPath=/issuer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}    #http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

# info endpoints configuration
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    java:
      version: ${java.version}

management:
  endpoints:
    web:
      exposure:
        include: ["health","prometheus","metrics","gateway","info"]
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

# logging
logging:
  file:
    path:  ${HOME}/Documents/ms_logs/${spring.application.name}-logs
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


