# global config
global:
  scrape_interval: 15s 	
  evaluation_interval: 15s 	

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
      - targets: 
        - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    # Override global default & scrape targets from this job
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-container:9090']

  - job_name: 'API-GATEWAY'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['API-GATEWAY:8989']

  - job_name: 'BOOK-MICROSERVICE'
    # Override global default & scrape targets from this job
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['BOOK-MICROSERVICE:8097']
      
  - job_name: 'ISSUER-MICROSERVICE'
    # Override global default & scrape targets from this job
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ISSUER-MICROSERVICE:8099']
