# global config
global:
  scrape_interval: 25s 	
  evaluation_interval: 25s 	

# Prometheus self monitoring
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.9:9090']

  - job_name: 'BOOK-MICROSERVICE Service Input'
    metrics_path: '/actuator/prometheus' 
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.7:8097']
        labels:
          application: 'BOOK-MICROSERVICE'
    basic_auth:
      username: User
      password: "password"

  - job_name: 'ISSUER-MICROSERVICE Service Input'
    metrics_path: '/actuator/prometheus' 
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.8:8099']
        labels:
          application: 'ISSUER-MICROSERVICE'
    basic_auth:
      username: User
      password: "password"

  - job_name: 'API-GATEWAY Service Input'
    metrics_path: '/actuator/prometheus' 
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.6:8099']
        labels:
          application: 'API-GATEWAY'
    basic_auth:
      username: User
      password: "password"
