server:
  port: 8099
  error:
    path: /error
    whitelabel:
      enabled: true

spring:
  application:
    name: ISSUER-MICROSERVICE
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:issuerdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  security:
    enabled: true
    user:
      name: Edureka
      password: password  # $2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
      roles: USER, ADMIN
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

app:
  security:
    cors:
      origin: http://localhost:3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
#  instance:
#    prefer-ip-address: false
#    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: [ "health","prometheus","metrics","info"]
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# info endpoints configuration
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    java:
      version: ${java.version}

# logging
logging:
  file:
    path:  /home/sask/Documents/edureka/ms_logs/${spring.application.name}-logs



#  #spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
