server:
  port: 8099
  error:
    path: /error

spring:
  application:
    name: ISSUER-MICROSERVICE
  cloud:
    config:
      import-check:
        enabled: false
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:issuerdb
    username: sa
    password: password
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    # DDL
    generate-dll: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: true
  security:
    enabled: true
    user:
      name: User
      password: password  # $2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
      roles: USER, ADMIN
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

app:
  security:
    cors:
      origin: http://localhost:3000

eureka:
  client:
    webclient:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

hystrix:
  dashboard:
    proxyStreamAllowList: '*'

# info endpoints configuration
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    java:
      version: ${java.version}

management:
  endpoints:
    jmx:
      exposure:
        include: ["health","prometheus","metrics","hystrix.stream"]
    web:
      exposure:
        include: ["health","prometheus","metrics","hystrix.stream"]
      base-path: /actuator
      cors:
        allowed-origins: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true


#Description:
#  No spring.config.import property has been defined
#Action:
#Add a spring.config.import=configserver: property to your configuration.
#  If configuration is not required add spring.config.import=optional:configserver: instead.
#  To disable this check, set spring.cloud.config.enabled=false or
#  spring.cloud.config.import-check.enabled=false.
