version: '3.8'

volumes:
  prom-data: {
    #external: true
  }
  graf-data: {
    #external: true
  }

services:

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus 
    volumes:
      - ./prometheus/:/etc/prometheus/
      - "prom-data/:/var/lib/prometheus/"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.listen-address=0.0.0.0:9095'
      # - '--storage.tsdb.path=/var/lib/prometheus'
      # - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      # - '--web.console.templates=/usr/share/prometheus/console' 
    ports:
      - "9095:9095"
    networks:
      - microservice_net
  #  --- # restart: unless-stopped

  grafana:
    container_name: grafana-container
    image: grafana/grafana
    #user: "$UID:$GID"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_DOMAIN: localhost
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      #- ./grafana/:/var/lib/grafana/
      - "graf-data/:/var/lib/grafana/"    
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./grafana/config
    ports:
      - "3030:3000"
    networks:
      - microservice_net
    # ----restart: unless-stopped
    depends_on:
      - prometheus

networks:
  microservice_net:
    name: microservice_net
    driver: bridge


