version: '3.8'

volumes:
  prom_data: {  }
  graf_data: {  }

services:
  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:v2.35.0 
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "prom_data/:/var/lib/prometheus/"
      - "./prometheus/:/etc/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.templates=/usr/share/prometheus/console'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - "9090:9090"
    networks:
      amazingms_net:
        ipv4_address: 172.20.0.9
       # restart: unless-stopped

  grafana:
    container_name: grafana-container
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    #user: admin #"$UID:$GID"
    environment:
      #GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource,vonage-status-panel'
      - GF_INSTALL_PLUGINS=https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource,grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel,grafana-simple-json-datasource,vonage-status-panel
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    volumes: 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"    
      - graf_data/:/var/lib/grafana/    
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config
    ports:
      - "3000:3000"
    networks:
      amazingms_net:
        ipv4_address: 172.20.0.10
    # ----restart: unless-stopped
    depends_on:
      - prometheus

networks:
  amazingms_net:
    external: 
      name: amazing-books-ms_amazingms_net  
      
