# global config
global:
  scrape_interval: 15s 	
  evaluation_interval: 15s 	

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# alert
# alerting:
#   alertmanagers:
#     - scheme: http
#     - static_configs:
#       - targets: 
#         - "alertmanager:9093"

# Prometheus self monitoring
scrape_configs:
  - job_name: 'prometheus'
    # Override global default & scrape targets from this job
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus-container:9090']

  - job_name: 'API-GATEWAY'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.20.0.6:8989']
        labels:
          group: 'API-GATEWAY MONITOR'

  - job_name: 'BOOK-MICROSERVICE'
    # Override global default & scrape targets from this job
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.7:8097']
        labels:
          group: 'BOOK-MICROSERVICE MONITOR'

  - job_name: 'ISSUER-MICROSERVICE'
    # Override global default & scrape targets from this job
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.8:8099']
        labels:
          group: 'ISSUER-MICROSERVICE MONITOR'
