
server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVICE
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0

# logging
logging:
  file:
    path: ${HOME}/ms_logs/${spring.application.name}-logs
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG